name: WhatsApp RSS Bot

on:
  # schedule:                              # ← comment out 
  #   - cron: '0 */6 * * *'                # Runs every 6 hours (UTC)
  workflow_dispatch:                      # still allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install feedparser twilio python-dotenv

      - name: Run WhatsApp RSS bot
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}
        run: |
          python script.py
